### ISSUE TITLE
Almost all area's involving shapes, do not display any shapes

### ISSUE THREAD

**Issue by Taustin442** [Taustin442/polygons#19]
This is what I see in almost every area of the index page.

![image](https://cloud.githubusercontent.com/assets/910711/10718684/0c993fe6-7b4f-11e5-8701-6bef03168e2d.png)
![image](https://cloud.githubusercontent.com/assets/910711/10718689/203ffd82-7b4f-11e5-8727-9fad4ac887ce.png)

This is the only section that includes shapes
![image](https://cloud.githubusercontent.com/assets/910711/10718692/302d7c7e-7b4f-11e5-990f-eab2274c094f.png)

**Comment by chandni881** [comment]
It's doing the same thing with me!

**Comment by BryanJll** [comment]
What browser and version are you all using?

I'm using firefox and I just dowloaded a zip of the latest taustin project and it's working fine with the new images.

**Comment by BryanJll** [comment]
Live preview in Chrome also works in my code ide.  

The error comes from the security error:

SecurityError: Blocked a frame with origin from accessing a cross-origin frame

This appears to be because when you open in chrome directly from your file browser it doesn't authenticate correctly.  I will look into it further.

**Comment by Taustin442** [comment]
Tested with the zip in addition to cloning the repo.
tested with chrome Version 46.0.2490.71 m
Tested by opening the index.html file in the main directory, which opened by default in chrome for me.

Upon further inspection it works in firefox and internet explorer for me.

**Comment by Taustin442** [comment]
Also in chrone, the banner does not shift as you scholl down

**Comment by BryanJll** [comment]
Luckily the two things are related.  Problem is in intro.js

As I suspected loading from a local file directory does not set up the correct server info which throws an error.  The error is triggered in the scroll intro and background javascript file.  Solutions include test using a fake local server, test the website by hosting it on a site real quick, use brackets ide, use firefox and ie.  I'll look into more options before I close the issue.

**Comment by Taustin442** [comment]
This has been fixed in #20 and will now be closed
